// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6N4qIK98wkkCOQfuWilgiBxa49bV5Ls',
    appId: '1:760382909707:web:5ba5f69de988550b43060e',
    messagingSenderId: '760382909707',
    projectId: 'largecapacitycontainer',
    authDomain: 'largecapacitycontainer.firebaseapp.com',
    storageBucket: 'largecapacitycontainer.appspot.com',
    measurementId: 'G-4HV1PCXYT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjs8vzybECIOcTs5jT2Lom2ZGJPlRYF-Y',
    appId: '1:760382909707:android:dfa2b9990005d9fc43060e',
    messagingSenderId: '760382909707',
    projectId: 'largecapacitycontainer',
    storageBucket: 'largecapacitycontainer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpl1iK3_Q70-zHmsBPDhB2IKSK4SG48o',
    appId: '1:760382909707:ios:650c9fe6b8278a7d43060e',
    messagingSenderId: '760382909707',
    projectId: 'largecapacitycontainer',
    storageBucket: 'largecapacitycontainer.appspot.com',
    iosClientId: '760382909707-4vnb6mjkladbeqgcp7iv2nuh6d7bumo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.largeCapacityContainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxpl1iK3_Q70-zHmsBPDhB2IKSK4SG48o',
    appId: '1:760382909707:ios:650c9fe6b8278a7d43060e',
    messagingSenderId: '760382909707',
    projectId: 'largecapacitycontainer',
    storageBucket: 'largecapacitycontainer.appspot.com',
    iosClientId: '760382909707-4vnb6mjkladbeqgcp7iv2nuh6d7bumo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.largeCapacityContainer',
  );
}
